---
title: "CodeBook.md"
author: "jm"
date: "9/22/2020"
output: html_document
---
# Introduction

This dataset summarises the average values of the 561 measurements obtained in the Human Activity Recognition Using Smartphones Dataset, for each activity and each subject. 

There were a total of 30 subjects, who each performed six activities while wearing a smartphone with embedded sensors (acceleromter and gyroscope) on their waist. The six activities included: (1) walking, (2) walking upstairs, (3) walking downstairs, (4) sitting, (5) standing and (6) laying. 

The signals used to estimate the 561 variables in this dataset included:

* tBodyAcc-XYZ
* tGravityAcc-XYZ
* tBodyAccJerk-XYZ
* tBodyGyro-XYZ
* tBodyGyroJerk-XYZ
* tBodyAccMag
* tGravityAccMag
* tBodyAccJerkMag
* tBodyGyroMag
* tBodyGyroJerkMag
* fBodyAcc-XYZ
* fBodyAccJerk-XYZ
* fBodyGyro-XYZ
* fBodyAccMag
* fBodyAccJerkMag
* fBodyGyroMag
* fBodyGyroJerkMag
* gravity

The following variables were estimated from these signals:

* mean(): Mean value
* std(): Standard deviation
* mad(): Median absolute deviation 
* max(): Largest value in array
* min(): Smallest value in array
* sma(): Signal magnitude area
* energy(): Energy measure. Sum of the squares divided by the number of values. 
* iqr(): Interquartile range 
* entropy(): Signal entropy
* arCoeff(): Autorregresion coefficients with Burg order equal to 4
* correlation(): correlation coefficient between two signals
* maxInds(): index of the frequency component with largest magnitude
* meanFreq(): Weighted average of the frequency components to obtain a mean frequency
* skewness(): skewness of the frequency domain signal 
* kurtosis(): kurtosis of the frequency domain signal 
* bandsEnergy(): Energy of a frequency interval within the 64 bins of the FFT of each window.
* angle(): Angle between to vectors.


# Data Processing
A zip file containing the test and train datasets, activity labels and variable names was extracted from the course website. 

The test and train datasets were combined together.The activity labels were converted from its numeric form into the more descriptive activity names, and then added to the dataset. The variable names were also extracted from the list of features and added to the dataset. Trireplicates of certain variable names were found and these were renamed to ensure that each variable name was unique. 

The data was then grouped according to the type of activity and the subject ID. Average values of each variable were obtained according to this grouping to generate the final dataset.
